version: '3.8'

networks:
  shared_network:
    driver: bridge

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=project
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres-password
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - shared_network
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        command: redis-server --save ""
        networks:
            - shared_network

    backend-migration:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
        entrypoint: [ "sh", "-c", "make migrate" ]
        networks:
            - shared_network
        depends_on:
            - postgres


    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        command: uvicorn app.application:app --host 0.0.0.0 --port 8000
        ports:
            - "8000:8000"
        networks:
            - shared_network
        depends_on:
            - backend-migration

volumes:
    postgres-data:
        driver: local
